# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 103f50d05f155695e25cfe387441a9b6e6bdf23904ab900141fe2f718ae93c76f35c5ca140e125aaf2af3ffb6faad9c1ed9039245e997ef81af5684f032539e4

test:
  secret_key_base: 3954ea6c05a8d565fb4a0f70e9c6bfb6f4c7feab59320d817b52d043137c28b2e288941ac61aa8c3502c5b679168741e4df7877b7fbc8140d2c4fe308fed63fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
